### ISSUE TITLE
Cannot import from parent directory

### ISSUE THREAD

**Issue by fineline** [prisma/graphql-import#308]
Using the following:

```
# import Student from "../datamodel.graphql"
```

gives error:

```
GraphQLError: Syntax Error: Cannot parse the unexpected character "/".
    at syntaxError (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql/14.2.0/node_modules/graphql/error/syntaxError.js:24:10)
    at readToken (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql/14.2.0/node_modules/graphql/language/lexer.js:314:32)
    at Object.lookahead (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql/14.2.0/node_modules/graphql/language/lexer.js:62:43)
    at Object.advanceLexer [as advance] (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql/14.2.0/node_modules/graphql/language/lexer.js:52:33)
    at expectToken (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql/14.2.0/node_modules/graphql/language/parser.js:1429:11)
    at many (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql/14.2.0/node_modules/graphql/language/parser.js:1520:3)
    at parseDocument (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql/14.2.0/node_modules/graphql/language/parser.js:115:18)
    at Object.parse (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql/14.2.0/node_modules/graphql/language/parser.js:50:10)
    at getDocumentFromSDL (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql-import/0.7.1/node_modules/graphql-import/dist/index.js:119:26)
    at importSchema (/Users/tstewart/dev/test-prisma/node_modules/.registry.npmjs.org/graphql-import/0.7.1/node_modules/graphql-import/dist/index.js:71:20)
```

What is the correct syntax for importing from a parent directory?

**Comment by fineline** [comment]
I found this was actually a problem in my parameters to importSchema, the file path was invalid and so was trying to parse that as raw GraphQL.
